name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Hey, there! :wave: <br /><br /> This issue has been marked as **stale** and would be closed. <br /> Feel free to open it again if you have more questions :+1:'
        stale-pr-message: 'Hey, there! :wave: <br /><br /> This PR has been marked as **stale** and would be closed. <br /> Feel free to open it again if you have more questions :+1:'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 30
        days-before-close: 5
